name = "cloudflare-stagehand-example"
main = "src/index.ts"
workers_dev = true
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-08-16"
upload_source_maps = true

[browser]
binding = "MYBROWSER"

[ai]
binding = "AI"
